first implementation ionic appender
Penbase/ionic-logging-service pull request #1
Opened 2020-10-09 15:23 UTC by VictorPenbase

Ajout ionic appender

2020-10-13 07:00 UTC, sylvainPenbase commented on projects/ionic-logging-service/src/lib/ionic-storage-appender.model.spec.ts
> +		storage = TestBed.inject(Storage);
```
		storage = TestBed.inject(Storage);
```

Je suis surpris de cette notation. Spontanément, j'aurais mis 

```
		storage = TestBed.get(Storage);
```

2020-10-13 07:02 UTC, sylvainPenbase commented on projects/ionic-logging-service/src/lib/ionic-storage-appender.model.spec.ts
> +			spyOn(storage, "get").and.returnValue(Promise.resolve("[{ \"level\": \"INFO\", \"message\": [], \"timeStamp\": \"2020-10-12T07:24:43.475Z\" }]"));
Il faudrait mettre la valeur de retour dans une variable

2020-10-13 07:03 UTC, VictorPenbase commented on projects/ionic-logging-service/src/lib/ionic-storage-appender.model.spec.ts
> +		storage = TestBed.inject(Storage);
Il est en dernière version de Karma et get est deprecated. Ils l'ont remplacé par inject.

2020-10-13 07:09 UTC, VictorPenbase commented on projects/ionic-logging-service/src/lib/ionic-storage-appender.model.spec.ts
> +			spyOn(storage, "get").and.returnValue(Promise.resolve("[{ \"level\": \"INFO\", \"message\": [], \"timeStamp\": \"2020-10-12T07:24:43.475Z\" }]"));
Ok done

2020-10-13 07:26 UTC, sylvainPenbase requested changes
Quelques petites remarques : 
 * des textes faisant référence à LocalStorage alors qu'on est sur du IonicStorage
* des questions sur les tests

2020-10-13 07:26 UTC, sylvainPenbase commented on projects/ionic-logging-service/src/lib/ionic-storage-appender.model.spec.ts
> +	describe("localStorageKey", () => {
```suggestion
	describe("ionicStorageKey", () => {
```

2020-10-13 07:26 UTC, sylvainPenbase commented on projects/ionic-logging-service/src/lib/ionic-storage-appender.model.spec.ts
> +		it("throws error if configuration contains no localStorageKey", () => {
```suggestion
		it("throws error if configuration contains no ionicStorageKey", () => {
```

2020-10-13 07:26 UTC, sylvainPenbase commented on projects/ionic-logging-service/src/lib/ionic-storage-appender.model.spec.ts
> +		it("throws error if configuration contains empty localStorageKey", () => {
```suggestion
		it("throws error if configuration contains empty ionicStorageKey", () => {
```

2020-10-13 07:26 UTC, sylvainPenbase commented on projects/ionic-logging-service/src/lib/ionic-storage-appender.model.spec.ts
> +		it("throws an error if value from configuration is invalid", async () => {
aucune erreur n'est throw dans ce test, contrairement à la description. Je pense qu'il faudrait revoir simplement la description, sans forcément revoir le test

2020-10-13 07:26 UTC, sylvainPenbase commented on projects/ionic-logging-service/src/lib/ionic-storage-appender.model.spec.ts
> +			appender.doAppend(event);
pourquoi `.doAppend` et pas `.append` comme dans les autres tests ?

2020-10-13 07:26 UTC, sylvainPenbase commented on projects/ionic-logging-service/src/lib/ionic-storage-appender.model.spec.ts
> +	describe("getLocalStorageKey(): string", () => {
```suggestion
	describe("getIonicStorageKey(): string", () => {
```

2020-10-13 07:26 UTC, sylvainPenbase commented on projects/ionic-logging-service/src/lib/ionic-storage-appender.model.spec.ts
> +	describe("getMaxMessages(): number", () => {
Je pense que le test serait plus parlant si tu définissais le maxMessage par le IonicStorageConfiguration

2020-10-13 07:26 UTC, sylvainPenbase commented on projects/ionic-logging-service/src/lib/ionic-storage-appender.model.spec.ts
> +	describe("removeLogMessages(localeStorageKey: string): void", () => {
```suggestion
	describe("removeLogMessages(ionicStorageKey: string): void", () => {
```

2020-10-13 08:33 UTC, VictorPenbase commented on projects/ionic-logging-service/src/lib/ionic-storage-appender.model.spec.ts
> +			appender.doAppend(event);
Car c'est le test. 'doAppend' appelle 'append' le test est que si 'doAppend' à un lvl au-dessus de la config on n'appelle pas 'append'.

2020-10-14 06:52 UTC, sylvainPenbase approved these changes

2020-10-19 10:17 UTC, assanepenbase commented
@VictorPenbase : Il faudrait créer une branche `dev` et modifier la branche de base de cette pr.

2020-10-19 10:18 UTC, assanepenbase commented
Je viens de créer la `dev`. Tu peux l'utiliser.

2020-11-05 09:18 UTC, assanepenbase approved these changes

2020-11-05 11:18 UTC, merged