add remouve log
Penbase/ionic-logging-service pull request #11
Opened 2020-12-01 16:35 UTC by VictorPenbase

https://penbase.easyredmine.com/issues/9876

2020-12-02 09:43 UTC, sylvainPenbase requested changes
Quelques petites suggestions et remarques.

C'est intéressant car c'est sensiblement la même PR que j'avais faite pour la version 7, mais il n'y a pas les fichiers html liés à la doc. Ça rend la PR vachement plus lisible 👍

2020-12-02 09:43 UTC, sylvainPenbase commented on projects/ionic-logging-service/src/lib/logging.service.spec.ts
> +		storage = TestBed.get(Storage);
Il me semblait qu'avec la version de Jasmine, il fallait faire un inject et pas un get ?

2020-12-02 09:43 UTC, sylvainPenbase commented on projects/ionic-logging-service/src/lib/logging.service.ts
> +				console.log("configure set log levels level.loggerName=" + level.loggerName);
```suggestion
```

2020-12-02 09:43 UTC, sylvainPenbase commented on projects/ionic-logging-service/src/lib/logging.service.ts
> +			console.log("configure ionicStorageAppender");
```suggestion
```

2020-12-02 09:43 UTC, sylvainPenbase commented on projects/ionic-logging-service/src/lib/ionic-storage-appender.model.ts
> +	public async  clearLog(): Promise<void> {
```suggestion
	public async clearLog(): Promise<void> {
```

2020-12-04 10:14 UTC, sylvainPenbase approved these changes

2020-12-04 11:07 UTC, assanepenbase approved these changes

2020-12-07 07:42 UTC, merged